channels:
- conda-forge
dependencies:
- python=3.13.12
- pip<=24.3.1
- pip:
  - mlflow==3.3.2
  - cloudpickle==3.1.2
  - numpy==2.4.2
  - pandas==2.3.2
  - pyarrow==21.0.0
  - scikit-learn==1.7.2
  - scipy==1.17.0
name: mlflow-env
